Constants = {
    GRAVITY = 800,
    PLAYER_GRAVITY_JUMP = -500,
    MOB_GRAVITY_JUMP = -350,
    MOD_TRACKING_DISTANCE = 500,
    PLAYER_SPEED = 300,
    MOD_SPEED = 100,
    GROUND_Y = 400,
    TILE_SIZE = 32,
    ITEM_OBJECT_SIZE = 16,
    ACTION_DISTANCE = 32,
    EXPLOIT_SIZE = 10,
    MELEE_ATTACK_SIZE = 50,
    ARROW_SPEED = 800,
    PLAYER_SIZE = 64,
    WINDOW_WIDTH = 1200,
    WINDOW_HEIGHT = 800,
    WATER_SPEED_RATE = 0.5,
    INVINCIBLE_TIME = 0.5,
    COMMON_ACTION_FPS = 8,
    PLAYER_ACTION_DELAY = 0.6,
    APPLE_SPAWN_RATE = 0.05,
    RAMDOM_MOB_ATTACK_TIME = 3,
    DMG_INERTIA = 100,
    HUNGER_DMG_DELAY_TIME = 5,
    HUNGER_SPEED = 1 / 60, -- 1 per min
    BLOCK_DAMAGED_COLOR = { 0.3, 0.3, 0.3, 1 },
    OBJ_DAMAGED_COLOR = { 1, 0, 0, 1 },
    ENDERMAN_TELEPORT_MAX_Y = 100,
    ENDERMAN_TELEPORT_MIN_X = 150,
    ENDER_EYE_FLY_RANGE = { 32 * 6, 8 * 32 },
    ENDER_EYE_SPEED = 200,


    -- game object names
    OBJ_NAME_PLAYER = "PLAYER",
    OBJ_NAME_ZOMBIE = "ZOMBIE",
    OBJ_NAME_SKELETON = "SKELETON",
    OBJ_NAME_CREEPER = "CREEPER",
    OBJ_NAME_ENDERMAN = "ENDERMAN",
    OBJ_NAME_ENDER_DRAGON = "ENDER_DRAGON",
    OBJ_NAME_OBJECT = "GameObject",
    OBJ_NAME_WATER = "WATER",
    OBJ_NAME_DMG = "DMG",
    OBJ_NAME_BLOCK = "BLOCK",
    OBJ_NAME_BLOCK_APPLE = "BLOCK_APPLE",
    OBJ_NAME_BLOCK_LEAF = "BLOCK_LEAF",
    OBJ_NAME_BLOCK_WOOD = "BLOCK_WOOD",

    -- terrain
    MAP_WIDTH = 500,
    MAP_HEIGHT = 100,
    MAP_WATER_HEIGHT = 50,
    MAP_GENERATE_SCALE = 0.02,
    MAP_GENERATE_OFFSET = 0,

    -- item names
    ITEM_PICKAXE = "ITEM_PICKAXE",
    ITEM_SWORD = "ITEM_SWORD",
    ITEM_BOW = "ITEM_BOW",
    ITEM_ARROW = "ITEM_ARROW",
    ITEM_APPLE = "ITEM_APPLE",
    ITEM_WOOD = "ITEM_WOOD",
    ITEM_MEAT = "ITEM_MEAT",
    ITEM_EYE_OF_ENDER = "ITEM_EYE_OF_ENDER",
    ITEM_BLOCK_DIRT = "ITEM_BLOCK_DIRT",
    ITEM_BLOCK_LEAF = "ITEM_BLOCK_LEAF",
    ITEM_BLOCK_IRON = "ITEM_BLOCK_IRON",
    ITEM_BLOCK_DIAMOND = "ITEM_BLOCK_DIAMOND",

    -- weapon types
    WEAPON_TYPE_MELEE_2D = "WEAPON_TYPE_MELEE_2D",
    WEAPON_TYPE_MELEE_4D = "WEAPON_TYPE_MELEE_4D",
    WEAPON_TYPE_RANGE = "WEAPON_TYPE_RANGE",
    WEAPON_TYPE_NONE = "WEAPON_TYPE_NONE",

    -- block item type
    BLOCK_ITEM_DIRT = "BLOCK_ITEM_DIRT",
    BLOCK_ITEM_LEAF = "BLOCK_ITEM_LEAF",

    -- game events
    EVENT_GAMEOBJ_DESTROYED = "EVENT_GAMEOBJ_DESTROYED",
    EVENT_DROP_ITEM = "EVENT_DROP_ITEM",
    EVENT_EATING = "EVENT_EATING",
    EVENT_DAMAGED_OBJECT = "EVENT_DAMAGED_OBJECT",
    EVENT_PlAYER_SPAWN = "EVENT_PlAYER_SPAWN",

    -- item image mapping
    ITEM_IMAGE_MAPPING = {
        ITEM_PICKAXE = { 3, 3 },
        ITEM_SWORD = { 2, 3 },
        ITEM_BOW = { 1, 3 },
        ITEM_ARROW = { 0, 3 },
        ITEM_APPLE = { 4, 3 },
        ITEM_WOOD = { 2, 0 },
        ITEM_MEAT = { 5, 3 },
        ITEM_EYE_OF_ENDER = { 6, 3 },
        ITEM_BLOCK_DIRT = { 1, 0 },
        ITEM_BLOCK_LEAF = { 3, 0 },
        ITEM_BLOCK_IRON = { 7, 0 },
        ITEM_BLOCK_DIAMOND = { 8, 0 },
    },

}
return Constants
